name: Release to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.2.0
        uses: actions/setup-node@v2
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 19.2.0
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Test the project
        run: npm test
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
