name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 19.2.0
        uses: actions/setup-node@v1
        with:
          node-version: 19.2.0
      - name: Install dependencies
        run: npm install
      - name: Build the project
        run: npm run build
      - name: Test the project
        run: npm test
      - name: Authenticate with npm
        uses: actions/npm-auth@v2
        with:
          npm_auth: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish to npm
        run: npm publish
